repos:
- repo: https://github.com/adamchainz/django-upgrade
  rev: 1.23.1
  hooks:
  - id: django-upgrade
    args: [--target-version, "5.0"]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.6
  hooks:
    # Run the linter.
    - id: ruff
    # Run the formatter.
    - id: ruff-format
      args: [--line-length, "120"]
