# Generated by Django 5.1.4 on 2025-01-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifier", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricealert",
            name="target_price_direction",
            field=models.CharField(
                choices=[(">=", "Above or Equal"), ("<=", "Below or Equal")],
                default=">=",
                help_text="Direction of the target price",
                max_length=2,
            ),
        ),
    ]
