# Generated by Django 5.0 on 2024-08-13 12:31

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltenant",
            name="quota",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=accounts.models.TenantQuota.get_default_quota,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accounts.tenantquota",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="quota",
            field=models.ForeignKey(
                blank=True,
                default=accounts.models.TenantQuota.get_default_quota,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tenants",
                to="accounts.tenantquota",
            ),
        ),
    ]
