# Generated by Django 5.0 on 2024-02-23 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("main", "0016_tenant_status_tenant_main_tenant_status_883ca8_idx"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={},
        ),
        migrations.AlterField(
            model_name="customuser",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="main.tenant",
                verbose_name="Организация",
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["tenant"], name="accounts_cu_tenant__89cfba_idx"),
        ),
    ]
