# Generated by Django 5.0 on 2024-05-07 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_lifetime_hours",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "number_of_skus",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "manual_updates",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "scheduled_updates",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_quotas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ограничение",
                "verbose_name_plural": "Ограничения",
            },
        ),
    ]
