# Generated by Django 5.0 on 2024-07-02 08:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenantquota",
            name="manual_updates_limit",
        ),
        migrations.RemoveField(
            model_name="tenantquota",
            name="scheduled_updates_limit",
        ),
    ]
