# Generated by Django 5.0 on 2024-08-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_historicaltenant_balance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentplan",
            name="name",
            field=models.CharField(
                choices=[
                    ("БЕСПЛАТНЫЙ", "FREE"),
                    ("БИЗНЕС", "BUSINESS"),
                    ("ПРОФЕССИОНАЛ", "PROFESSIONAL"),
                    ("КОРПОРАТИВНЫЙ", "CORPORATE"),
                ],
                max_length=20,
            ),
        ),
    ]
