# Generated by Django 5.0 on 2024-05-07 12:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_userquota"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userquota",
            old_name="number_of_skus",
            new_name="max_skus",
        ),
    ]
