# Generated by Django 5.0 on 2024-05-08 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_rename_number_of_skus_userquota_max_skus"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
