# Generated by Django 5.0 on 2024-08-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_paymentplan_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentplan",
            name="name",
            field=models.CharField(
                choices=[
                    ("0", "ТЕСТОВЫЙ"),
                    ("1", "БЕСПЛАТНЫЙ"),
                    ("2", "БИЗНЕС"),
                    ("3", "ПРОФЕССИОНАЛ"),
                    ("4", "КОРПОРАТИВНЫЙ"),
                ],
                max_length=20,
            ),
        ),
    ]
