# Generated by Django 5.0 on 2024-09-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_paymentplan_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantquota",
            name="name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "ТЕСТОВАЯ"),
                    ("1", "БЕСПЛАТНАЯ"),
                    ("2", "БИЗНЕС"),
                    ("3", "ПРОФЕССИОНАЛ"),
                    ("4", "КОРПОРАТИВНЫЙ"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
