# Generated by Django 5.0 on 2024-06-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_userquota_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userquota",
            name="allowed_parse_units",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userquota",
            name="manual_updates",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userquota",
            name="max_allowed_skus",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userquota",
            name="scheduled_updates",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userquota",
            name="user_lifetime_hours",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
