# Generated by Django 5.0 on 2024-09-06 18:13

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_tenantquota_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentplan",
            name="name",
            field=models.CharField(
                choices=[
                    ("0", "ПЛАН ТЕСТОВЫЙ"),
                    ("1", "ПЛАН БЕСПЛАТНЫЙ"),
                    ("2", "ПЛАН БИЗНЕС"),
                    ("3", "ПЛАН ПРОФЕССИОНАЛ"),
                    ("4", "ПЛАН КОРПОРАТИВНЫЙ"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="paymentplan",
            name="quotas",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.tenantquota",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="quota",
            field=models.ForeignKey(
                blank=True,
                default=accounts.models.TenantQuota.get_default_quota,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tenants",
                to="accounts.tenantquota",
            ),
        ),
        migrations.AlterField(
            model_name="tenantquota",
            name="name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "КВОТА ТЕСТОВАЯ"),
                    ("1", "КВОТА БЕСПЛАТНАЯ"),
                    ("2", "КВОТА БИЗНЕС"),
                    ("3", "КВОТА ПРОФЕССИОНАЛ"),
                    ("4", "КВОТА КОРПОРАТИВНАЯ"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
