# Generated by Django 5.0 on 2024-06-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_userquota_allowed_parse_units_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userquota",
            name="allowed_parse_units",
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name="userquota",
            name="manual_updates",
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name="userquota",
            name="max_allowed_skus",
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name="userquota",
            name="scheduled_updates",
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name="userquota",
            name="user_lifetime_hours",
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
    ]
