# Generated by Django 5.0 on 2024-09-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_alter_paymentplan_name_alter_paymentplan_quotas_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltenant",
            name="price_change_threshold",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                help_text="Процент изменения цены для уведомлений (напр, 5%)",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="price_change_threshold",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                help_text="Процент изменения цены для уведомлений (напр, 5%)",
                max_digits=6,
            ),
        ),
    ]
