# Generated by Django 5.0 on 2024-09-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_historicaltenant_price_change_threshold_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltenant",
            name="price_change_threshold",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Процент изменения цены для уведомлений (напр, 5.00%)",
                max_digits=6,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="price_change_threshold",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Процент изменения цены для уведомлений (напр, 5.00%)",
                max_digits=6,
            ),
        ),
    ]
