# Generated by Django 5.0 on 2024-08-18 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_historicaltenant_quota_alter_tenant_quota"),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unix_timestamp", models.IntegerField()),
                ("signature", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "testing",
                    models.CharField(
                        choices=[("1", "True"), ("0", "False")],
                        default="0",
                        max_length=1,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("order_id", models.CharField(max_length=255)),
                ("client_email", models.CharField(max_length=255)),
                (
                    "success_url",
                    models.CharField(default="https://pay.modulbank.ru/success", max_length=255),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.tenant",
                    ),
                ),
            ],
        ),
    ]
