# Generated by Django 5.0 on 2024-10-22 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ["-id"]},
        ),
        migrations.RenameField(
            model_name="order",
            old_name="total_amount",
            new_name="amount",
        ),
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="main.order",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="testing",
            field=models.CharField(choices=[("1", "1"), ("0", "0")], default="0", max_length=1),
        ),
    ]
