# Generated by Django 5.1.4 on 2025-01-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.DecimalField(
                decimal_places=0,
                help_text="Цена товара в магазине с учетом СПП",
                max_digits=10,
                null=True,
            ),
        ),
    ]
