# Generated by Django 5.0 on 2024-05-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltenant",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Trialing"),
                    (2, "Active"),
                    (3, "Exempt"),
                    (4, "Canceled"),
                    (5, "Trial expired"),
                ],
                default=2,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Trialing"),
                    (2, "Active"),
                    (3, "Exempt"),
                    (4, "Canceled"),
                    (5, "Trial expired"),
                ],
                default=2,
            ),
        ),
    ]
