# Generated by Django 4.2.6 on 2023-10-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="spp",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
