# Generated by Django 5.0 on 2024-08-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="order_id",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
