# Generated by Django 4.2.6 on 2023-10-20 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_item_spp"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="seller_price",
            field=models.DecimalField(
                decimal_places=0,
                help_text="Цена товара от продавца",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.DecimalField(
                decimal_places=0,
                help_text="Цена товара в магазине с учетом СПП",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="sku",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
