# Generated by Django 5.0 on 2024-06-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_historicaltenant_status_alter_tenant_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltenant",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Free"),
                    (1, "Trialing"),
                    (2, "Active"),
                    (3, "Exempt"),
                    (4, "Canceled"),
                    (5, "Trial expired"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Free"),
                    (1, "Trialing"),
                    (2, "Active"),
                    (3, "Exempt"),
                    (4, "Canceled"),
                    (5, "Trial expired"),
                ],
                default=0,
            ),
        ),
    ]
