# Generated by Django 5.0 on 2024-11-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_payment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_intent",
            field=models.CharField(
                choices=[
                    ("SWITCH_PLAN", "Switch plan"),
                    ("ADD_TO_BALANCE", "Add to balance"),
                ],
                default="ADD_TO_BALANCE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="terminal_key",
            field=models.CharField(default="1728466408616DEMO", max_length=255),
        ),
    ]
