# Generated by Django 4.2.2 on 2023-06-22 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'default_permissions': ('add', 'change', 'delete'), 'permissions': (('view_product', 'Can view product'),), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
