# Generated by Django 5.0 on 2024-12-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_order_order_intent_alter_payment_terminal_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Сумма оплаты"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="merchant",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="payment",
            name="terminal_key",
            field=models.CharField(max_length=255),
        ),
    ]
