# Generated by Django 5.1.4 on 2025-01-08 01:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_item_seller_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="Цена товара в магазине с учетом СПП",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="seller_price",
            field=models.DecimalField(
                decimal_places=0,
                help_text="Цена товара от продавца",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
