# Generated by Django 5.0 on 2024-08-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_payment_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="merchant_id",
            field=models.CharField(default="f29e4787-0c3b-4630-9340-5dcfcdc9f85d", max_length=255),
        ),
    ]
