# Generated by Django 4.2.6 on 2023-10-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_item_sku"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="sku",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="spp",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
