# Generated by Django 5.0 on 2024-08-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_payment_merchant_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="merchant_id",
            new_name="merchant",
        ),
        migrations.AlterField(
            model_name="payment",
            name="signature",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="testing",
            field=models.CharField(choices=[("1", "1"), ("0", "0")], default="0", max_length=1),
        ),
    ]
