# Generated by Django 4.2.6 on 2023-10-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_item_sku_alter_item_spp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="spp",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
