# Generated by Django 4.2.6 on 2023-10-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_item_spp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="sku",
            field=models.CharField(default="12345", max_length=20),
            preserve_default=False,
        ),
    ]
