# Generated by Django 5.0 on 2024-10-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_item_is_notifier_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="signature",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="unix_timestamp",
        ),
        migrations.AddField(
            model_name="payment",
            name="client_name",
            field=models.CharField(blank=True, help_text="ФИО плательщика", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="client_phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="fail_url",
            field=models.CharField(
                default="https://securepay.tinkoff.ru/html/payForm/fail.html",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="terminal_key",
            field=models.CharField(default="test", max_length=255),
        ),
        migrations.AlterField(
            model_name="payment",
            name="merchant",
            field=models.CharField(default="200000001392761", max_length=255),
        ),
        migrations.AlterField(
            model_name="payment",
            name="success_url",
            field=models.CharField(
                default="https://securepay.tinkoff.ru/html/payForm/success.html",
                max_length=255,
            ),
        ),
    ]
