# Generated by Django 5.0 on 2024-10-15 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_alter_historicaltenant_price_change_threshold_and_more"),
        ("main", "0009_remove_payment_signature_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="order_id",
            new_name="payment_id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="description",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="fail_url",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="receipt_items",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="success_url",
        ),
        migrations.AddField(
            model_name="payment",
            name="is_successful",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(blank=True, max_length=255, unique=True)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("CANCELED", "Canceled"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.tenant",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="main.order",
            ),
            preserve_default=False,
        ),
    ]
