# Generated by Django 4.2.6 on 2024-01-01 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_rename_date_added_price_created_at_item_created_at_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Printer",
        ),
    ]
