# Generated by Django 4.2.6 on 2024-01-07 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_delete_printer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interval", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "time_unit",
                    models.CharField(
                        choices=[
                            ("minutes", "Минут"),
                            ("hours", "Часов"),
                            ("days", "Дней"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="schedule",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("interval", "Интервал"), ("cronjob", "CronJob")],
                        max_length=50,
                    ),
                ),
                (
                    "interval",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="main.interval"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="main.item"),
                ),
                (
                    "schedule",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="main.schedule"),
                ),
            ],
        ),
    ]
