# Generated by Django 4.2.6 on 2024-01-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_interval_item_schedule_schedule_itemschedule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interval",
            name="time_unit",
        ),
        migrations.AddField(
            model_name="interval",
            name="period",
            field=models.CharField(
                choices=[("minutes", "Минуты"), ("hours", "Часы"), ("days", "Дни")],
                default="hours",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="interval",
            name="interval",
            field=models.IntegerField(),
        ),
    ]
