# Generated by Django 4.2.6 on 2024-01-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_remove_interval_time_unit_interval_period_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="interval",
        ),
        migrations.AddField(
            model_name="schedule",
            name="cronjob_value",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="CronJob"),
        ),
        migrations.AddField(
            model_name="schedule",
            name="interval_value",
            field=models.IntegerField(blank=True, null=True, verbose_name="Каждые"),
        ),
        migrations.AddField(
            model_name="schedule",
            name="period",
            field=models.CharField(
                choices=[("minutes", "Минут"), ("hours", "Часов"), ("days", "Дней")],
                default="hours",
                max_length=100,
            ),
        ),
        migrations.DeleteModel(
            name="Interval",
        ),
    ]
