# Generated by Django 4.2.6 on 2024-01-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_remove_schedule_interval_schedule_cronjob_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="period",
            field=models.CharField(
                choices=[
                    ("seconds", "Секунд"),
                    ("minutes", "Минут"),
                    ("hours", "Часов"),
                    ("days", "Дней"),
                ],
                default="hours",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="type",
            field=models.CharField(
                choices=[("interval", "Интервал"), ("cronjob", "CronJob")],
                default="interval",
                max_length=50,
                verbose_name="Тип расписания",
            ),
        ),
    ]
