# Generated by Django 5.0 on 2024-02-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0015_alter_schedule_interval_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Trialing"),
                    (2, "Active"),
                    (3, "Exempt"),
                    (4, "Canceled"),
                    (5, "Trial expired"),
                ],
                default=1,
            ),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["status"], name="main_tenant_status_883ca8_idx"),
        ),
    ]
