# Generated by Django 4.2.10 on 2024-03-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0017_historicaltenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="period",
            field=models.CharField(
                blank=True,
                choices=[
                    ("seconds", "Секунд"),
                    ("minutes", "Минут"),
                    ("hours", "Часов"),
                    ("days", "Дней"),
                ],
                default="hours",
                max_length=100,
            ),
        ),
    ]
