name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip' # caching pip dependencies

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Perform migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          EVENTLET_NO_GREENDNS: yes  # https://github.com/aiwaves-cn/agents/issues/94

      - name: Run tests with coverage info
        run: pytest -n 4 --migrations --cov-config=.coveragerc --cov=. tests/
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_ENABLED: 'off'
          EVENTLET_NO_GREENDNS: yes

#        Uncomment it for deployment checks (https://github.com/igorsimb/mp-monitor/issues/63)
#      - name: Check deploy configuration
#        run: python manage.py check --deploy --fail-level WARNING
